#!/bin/bash
rm .bashrc
clear
pkg update && pkg i x11-repo wget git
while true; do
clear
    echo "Nhập tên của bạn:"
 read user
    clear
sleep 1
    echo  "Bây giờ, bạn tên là $user."
sleep 3
clear
sleep 1
    echo "Bạn chắc chắn muốn dùng tên này chứ ? (C/k) :"
 read confirmation
    
    if [ "$confirmation" = "C" ] || [ "$confirmation" = "c" ]; then

        echo "export USER=\"$user\"" >> ~/.bashrc
		echo "PS1='\[\e[38;5;13m\]$user \[\e[38;5;11m\]\w\[\e[m\] \[\e[38;5;10m\]> \[\e[m\]'" >> .bashrc
clear
sleep 1

echo "$user có cần tùy chỉnh motd không? (C/k)"
read i
if [ "$i" = "C" ] || [ "$i" = "c" ]; then
clear
    rm /data/data/com.termux/files/usr/etc/motd
    echo "Vui lòng nhập những thứ mà bạn muốn ghi (dòng này sẽ xuất hiện khi đăng nhập):"
    read motd
    echo "export motd=\"$motd\"" >> ~/.bashrc
    echo "$motd      


" >> /data/data/com.termux/files/usr/etc/motd

clear
elif [ "$i" = "K" ] || [ "$i" = "k" ]; then
    return 0
fi
		echo "Bạn có muốn cài đặt toàn bộ setup của C-Kakao chứ ? (Bao gồm mobox, pd, proot, i3 config v.v) (C/k):"
read a

if [ "$a" = "C" ] || [ "$a" = "c" ]; then
pkg i git wget proot-distro proot feh i3 tur-repo x11-repo polybar rofi termux-x11-nightly

sleep 1
clear
curl -s -o ~/x https://raw.githubusercontent.com/NekoKatoriChan/mobox/main/install && . ~/x
sleep 3
		sleep 2
wget https://raw.githubusercontent.com/NekoKatoriChan/Neko-silly-termux-setup/main/file/config
wget https://github.com/NekoKatoriChan/Neko-silly-termux-setup/raw/main/file/Arch-chan_to.png
mkdir ~/.config/i3/
mv ~/config ~/.config/i3/
rm -rf ~/Neko-silly-termux-setup

rm uwu.gz
rm setup

	elif [ "$i" = "K" ] || [ "$i" = "k" ]; then
    return 0
fi

        echo "$user nên khởi động lại Termux hoặc nhập "source .bashrc" để áp dụng thay đổi."
sleep 3
	clear
echo "mod1 là alt nếu $user chưa biết"
clear
	break        
    elif [ "$confirmation" = "K" ] || [ "$confirmation" = "k" ]; then
        echo "Hãy nhập lại tên."
    else
        echo "Lựa chọn không hợp lệ. Vui lòng nhập 'C' hoặc 'K'."
    fi

done


