#!/bin/bash
FILE="$HOME/.meow
if [ ! -f "$FILE"]; then
rm .bashrc
clear
pkg update && pkg i x11-repo wget git
while true; do
clear
    echo "Nhập tên của bạn:"
 read user
    clear
sleep 1
    echo  "Bây giờ, bạn tên là $user."
sleep 3
clear
sleep 1
    echo "Bạn chắc chắn muốn dùng tên này chứ ? (C/k) :"
 read confirmation
    
    if [ "$confirmation" = "C" ] || [ "$confirmation" = "c" ]; then

        echo "export USER=\"$user\"" >> ~/.bashrc
		echo "PS1='\[\e[38;5;13m\]$user \[\e[38;5;11m\]\w\[\e[m\] \[\e[38;5;10m\]> \[\e[m\]'" >> .bashrc
clear
sleep 1

echo "$user có cần tùy chỉnh motd không? (C/k)"
read i
if [ "$i" = "C" ] || [ "$i" = "c" ]; then
clear
    rm /data/data/com.termux/files/usr/etc/motd
    echo "Vui lòng nhập những thứ mà bạn muốn ghi (dòng này sẽ xuất hiện khi đăng nhập):"
    read motd
    echo "export motd=\"$motd\"" >> ~/.bashrc
    echo "$motd      


" >> /data/data/com.termux/files/usr/etc/motd

clear
elif [ "$i" = "K" ] || [ "$i" = "k" ]; then
    return 0
fi
else
clear
echo "Vui lòng chọn cách setup
[1] Cài i3
[2] Đổi tên
[3] Cài mobox
[4] Thoát
"

read real
if [ $real = "1" ]; then
apt install i3 -y
elif [ $real = "2" ]; then
rm .bashrc
clear
pkg update && pkg i x11-repo wget git
while true; do
clear
    echo "Nhập tên của bạn:"
 read user
    clear
sleep 1
    echo  "Bây giờ, bạn tên là $user."
sleep 3
clear
sleep 1
    echo "Bạn chắc chắn muốn dùng tên này chứ ? (C/k) :"
 read confirmation

    if [ "$confirmation" = "C" ] || [ "$confirmation" = "c" ]; then

        echo "export USER=\"$user\"" >> ~/.bashrc
                echo "PS1='\[\e[38;5;13m\]$user \[\e[38;5;11m\]\w\[\e[m\] \[\e[38>
clear
sleep 1
clear
elif [ $real = "3" ]; then
curl -s -o ~/x https://raw.githubusercontent.com/NekoKatoriChan/mobox-vietnamese/refs/heads/main/install && . ~/x
else
exit
fi

